# Generated by Django 5.1.6 on 2025-02-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0003_usuario_medalla_usuario_puntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.usuario')),
            ],
        ),
    ]
