# Generated by Django 5.1.6 on 2025-02-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insignia',
            name='imagen',
            field=models.ImageField(upload_to='insignias/'),
        ),
    ]
