# Generated by Django 5.1.6 on 2025-02-24 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
        ('registro', '0002_remove_usuario_apellido_remove_usuario_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='medalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.medalla'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
