# Generated by Django 5.1.6 on 2025-02-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_usuario_medalla_usuario_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuarios/default.jpg', upload_to='usuario/'),
        ),
    ]
